title: Polyploidbreeding
logo: /assets/img/logo.png
description: [PRIN 2022 - Settore LS2](https://www.mur.gov.it/it/atti-e-normativa/decreto-direttoriale-n-752-del-1-6-2023)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
