title: Polyploidbreeding
logo: /assets/logo/logo_600x600_white.png
description: PRIN 2022 (Settore LS2)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Defaults
 defaults:
   # _posts
   - scope:
     values:
       mathjax: true
