title: Polyploidbreeding
logo: /assets/img/logo.png
description: Expanding the toolbox for cereal breeding - high-throughput genomics, 2D-3D phenomics and artificial intelligence for breeding with increasing genome complexity, from barley to durum and bread wheat (POLYPLOIDBREEDING 4.0) [PRIN 2022] 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
