on:
  fork:
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
